package presentacion;

public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        mnuMantenedor = new javax.swing.JMenu();
        mnuiGerente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Concesionario");

        mnuMantenedor.setText("Mantenedor");

        mnuiGerente.setMnemonic('G');
        mnuiGerente.setText("Gerente");
        mnuiGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiGerenteActionPerformed(evt);
            }
        });
        mnuMantenedor.add(mnuiGerente);

        menuBar.add(mnuMantenedor);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuiGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiGerenteActionPerformed
        FrmGerente aplicacion = new FrmGerente(this);
        aplicacion.setVisible(true);
    }//GEN-LAST:event_mnuiGerenteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuMantenedor;
    private javax.swing.JMenuItem mnuiGerente;
    // End of variables declaration//GEN-END:variables
}
